### ISSUE TITLE
Question about Circom frontend for Hypernova

### ISSUE THREAD

**Issue by yugocabrio** [privacy-scaling-explorations/sonobe#103]
Hello, 
I understand that Hypernova's Augmented Circuit has to be represented as CCS. So my question is does `generate_step_constraints` in the `FCircuit` also have to be represented as CCS to conduct HyperNova's folding?
I wrote the code that converts circom-compat's R1CS to Sonobe's R1CS [at this PR](https://github.com/privacy-scaling-explorations/sonobe/pull/26), but I changed to use cricom-compat's `generate_constraints` function in the `generate_step_constraints` of Sonobe. However, I feel that I should have adopted the first approach when I consider HyperNova and see the circom-compat update because it is easy to convert from R1CS to CCS.
What do you think about this and how would the approach to circom for Hypernova be best?

**Comment by arnaucube** [comment]
The R1CS to CCS is pretty direct (eg. [sonobe/folding-schemes/src/ccs/mod.rs#L73](https://github.com/privacy-scaling-explorations/sonobe/blob/ed1faee6bfdf9eb484a0b5bc6196896cc250abed/folding-schemes/src/ccs/mod.rs#L73)), so the approach that we're currently using is that the HyperNova's AugmentedFCircuit is defined with normal arkworks code which generates the R1CS, and we 'compute' the CCS from that R1CS ('compute' with quotes because it is not computing much, is just re-labeling some parameters to convert it to CCS to work with it later in HyperNova), which then is folded following HyperNova NIMFS scheme.
