### ISSUE TITLE
WASM IO compat

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/sonobe#147]
In this crate, we rely on functions that require reading `.r1cs` and `.wasm` files from the user's computer in order to be able to generate folding circuits.

The problem is that when we try to use `sonobe` in `wasm` (particularly in the browser) this crate only knows 1 way to get served this two files [and it's though file paths that will then be read](https://github.com/privacy-scaling-explorations/sonobe/blob/f6a70fe1d06bddfd469f8dbda3c0d10c53e082c5/folding-schemes/src/frontend/circom/utils.rs#L49).

So an alternative is needed that is compatible with `in-browser file reading`.

One good example is how is done in [Nova-Scotia](https://github.com/nalinbhardwaj/Nova-Scotia/blob/main/src/circom/wasm.rs). But with this, we are only able to fetch stuff from a website. 

This can be a low-hanging-fruit to enable a very minimal browser-compat. We should later evaluate if we should also try to go for other alternatives like using [FileReader from MDN web-docs](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) which is available in toolkits like [gloo](https://github.com/rustwasm/gloo). Specifically, [gloo-file](https://github.com/rustwasm/gloo/tree/master/crates/file).

A final option is to use [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage#instance_methods) which should allow us to let the developers of apps load the file with JS or whatever it is, and then to provide a key with which this data was stored with and let us query it from Rust obtaining the file contents which we can then pass to `sonobe` to do it's work.

IMO, we should go for the Nova-Scotia approach. Which is simple and easy to implement without trouble. And later, we can figure out if we need to improve this or not.

**Comment by arnaucube** [comment]
Thank you very much for delving into this! :raised_hands: 
Yes, I think that it makes sense to move forward with updating our fork of circom-compat to add this feature, since it already contains updates (eg. abstracting the field over which the lib works (the original repo only works over BN254's Fr field), and also updates the way how public inputs are handled to be able to specify public inputs so that we can use it as frontend for the IVC).
Once we have all this working and stable, we can prepare a PR to circom-compat's upstream, since probably will benefit other users of the library all the changes that we're making, but at least in this way we can move forward and use the lib in the browser already ^^

**Comment by CPerezz** [comment]
#149 definitely fixed this.

I think we can close the issue and revisit it in the future if further improved support is required.
