### ISSUE TITLE
Decide commitment openings approach for the Decider

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/sonobe#20]
Once #19 is done, we will still need to check the commitment openings. If done in-circuit it will be expensive, another option is to do it onchain. We will need to explore and do some tests to see the feasibility of the approaches.

**Comment by ashWhiteHat** [comment]
Hi there
I have a question.
Does `Decider` mean that the way to prove [HyperNova verification](https://eprint.iacr.org/2023/573.pdf#page=27&zoom=100,100,520) with on-chain verifier?

I would appreciate it if you could reply.
Thank you.

**Comment by arnaucube** [comment]
Hi ^^
For the moment we are focusing on Nova, so the verifier in this case would be verifying Nova proofs onchain.

**Comment by ashWhiteHat** [comment]
Thank you for the reply.

Are you going to verify the same with the [nova paper verification algorithm](https://eprint.iacr.org/2021/370.pdf#page=19&zoom=100,100,600)?

In a naive way, the verifier cost increases linearly depending on step number $i$.
Especially, I think the proof size is too large to handle it with on-chain because it's r1cs witness and instance.

**Comment by ashWhiteHat** [comment]
Ah sorry
It doesn't increase linearly
I thought $Π_i:  ((Ui, Wi),(ui,wi))$ was array of witness and instance of relaxed r1cs but it's a single step proof

**Comment by arnaucube** [comment]
Closing, as after some iterations it was consolidated as it is described in the docs: https://privacy-scaling-explorations.github.io/sonobe-docs/design/nova-decider-onchain.html
and done across the PRs #79, #62, #63, #66, #49.
